exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("games")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("games").insert([
        {
          id: 151,
          location: "Denver Park Complex",
          city: "Denver",
          // day selction
          day: "Monday",
          // time selection
          time: "Night",
          // level
          level: "Open",
          // field type
          surface: "Turf",
          // goals
          goals: "Netless",
          // info
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          // stats
          stats_games_completed: 45,
          stats_total_players: 118,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 225,
          location: "Washington Park",
          city: "Washington Park",
          day: "Monday",
          time: "Morning",
          level: "Normal",
          surface: "Concrete",
          goals: "None",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "None",
          stats_games_completed: 13,
          stats_total_players: 45,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 403,
          location: "Boulder High",
          city: "Boulder",
          day: "Tuesday",
          time: "Night",
          level: "Competitive",
          surface: "Concrete",
          goals: "None",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 22,
          stats_total_players: 45,
          stats_player_count: 9,
          phone_number: 5033136362
        },
        {
          id: 509,
          location: "Golden Sports Park",
          city: "Golden",
          day: "Tuesday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "None",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 88,
          stats_total_players: 29,
          stats_player_count: 9,
          phone_number: 5033136362
        },
        {
          id: 480,
          location: "Arvada Park",
          city: "Arvada",
          day: "Tuesday",
          time: "Night",
          level: "Normal",
          surface: "Grass",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "None",
          stats_games_completed: 29,
          stats_total_players: 119,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 506,
          location: "Sayian Field",
          city: "Ft. Collins",
          day: "Wednesday",
          time: "Day",
          level: "Competitive",
          surface: "Concrete",
          goals: "Netless",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "None",
          stats_games_completed: 3,
          stats_total_players: 83,
          stats_player_count: 7,
          phone_number: 5033136362
        },
        {
          id: 571,
          location: "Congress Park",
          city: "Capitol Hill",
          day: "Wednesday",
          time: "Night",
          level: "Competitive",
          surface: "Turf",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 83,
          stats_total_players: 288,
          stats_player_count: 5,
          //twilio
          phone_number: 5033136362
        },
        {
          id: 258,
          location: "Estes Park",
          city: "Estes Park",
          day: "Thursday",
          time: "Morning",
          level: "Normal",
          surface: "Concrete",
          goals: "None",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "None",
          stats_games_completed: 21,
          stats_total_players: 24,
          stats_player_count: 12,
          phone_number: 5033136362
        },
        {
          id: 309,
          location: "Colfax Sports Complex",
          city: "Denver",
          day: "Thursday",
          time: "Morning",
          level: "Competitive",
          surface: "Turf",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 41,
          stats_total_players: 119,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 608,
          location: "Longmont Sports Park",
          city: "Longmont",
          day: "Thursday",
          time: "Night",
          level: "Open",
          surface: "Concrete",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 11,
          stats_total_players: 64,
          stats_player_count: 2,
          phone_number: 5033136362
        },
        {
          id: 808,
          location: "North High School",
          city: "City Park",
          day: "Thursday",
          time: "Day",
          level: "Normal",
          surface: "Dirt",
          goals: "None",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 92,
          stats_total_players: 30,
          stats_player_count: 13,
          phone_number: 5033136362
        },
        {
          id: 623,
          location: "Aroura Sports Park",
          city: "Aroura",
          day: "Friday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "None",
          stats_games_completed: 20,
          stats_total_players: 97,
          stats_player_count: 1,
          phone_number: 5033136362
        },
        {
          id: 066,
          location: "Sloan's Lake",
          city: "Lakewood",
          day: "Friday",
          time: "Morning",
          level: "Competitive",
          surface: "Grass",
          goals: "Netless",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 64,
          stats_total_players: 211,
          stats_player_count: 15,
          phone_number: 5033136362
        },
        {
          id: 770,
          location: "Overland Park",
          city: "Denver",
          day: "Friday",
          time: "Night",
          level: "Competitive",
          surface: "Turf",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 42,
          stats_total_players: 109,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 165,
          location: "RiNo Athletic Fields",
          city: "River North",
          day: "Friday",
          time: "Day",
          level: "Normal",
          surface: "Turf",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 72,
          stats_total_players: 252,
          stats_player_count: 3,
          phone_number: 5033136362
        },
        {
          id: 651,
          location: "Boulder Indoor",
          city: "Boulder",
          day: "Friday",
          time: "Night",
          level: "Open",
          surface: "Turf",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 22,
          stats_total_players: 31,
          stats_player_count: 11,
          phone_number: 5033136362
        },
        {
          id: 883,
          location: "Cheeseman Park ",
          city: "Cap Hill",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 29,
          stats_total_players: 125,
          stats_player_count: 1,
          phone_number: 5033136362
        },
        {
          id: 083,
          location: "Boulder Sports Park",
          city: "Boulder",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Turf",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 52,
          stats_total_players: 221,
          stats_player_count: 1,
          phone_number: 5033136362
        },
        {
          id: 449,
          location: "Southpark Park",
          city: "Fairplay",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 21,
          stats_total_players: 69,
          stats_player_count: 4,
          phone_number: 5033136362
        },
        {
          id: 983,
          location: "Curtis Park",
          city: "River North",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 33,
          stats_total_players: 17,
          stats_player_count: 3,
          phone_number: 5033136362
        },
        {
          id: 764,
          location: "Parker Park",
          city: "Parker",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 42,
          stats_total_players: 93,
          stats_player_count: 1,
          phone_number: 5033136362
        },
        {
          id: 283,
          location: "Broomfield Field",
          city: "Denver",
          day: "Sunday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 10,
          stats_total_players: 51,
          stats_player_count: 7,
          phone_number: 5033136362
        },
        {
          id: 285,
          location: "Vail Park",
          city: "Vail",
          day: "Sunday",
          time: "Night",
          level: "Normal",
          surface: "Dirt",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "None",
          stats_games_completed: 28,
          stats_total_players: 46,
          stats_player_count: 19,
          phone_number: 5033136362
        },
        {
          id: 993,
          location: "Steamboat Field",
          city: "Steamboat",
          day: "Sunday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 18,
          stats_total_players: 41,
          stats_player_count: 15,
          phone_number: 5033136362
        },
        {
          id: 114,
          location: "Englewood Complex",
          city: "Englewood",
          day: "Sunday",
          time: "Night",
          level: "Open",
          surface: "Grass",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 32,
          stats_total_players: 80,
          stats_player_count: 0,
          phone_number: 5033136362
        },
        {
          id: 698,
          location: "City Park",
          city: "Denver",
          day: "Sunday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 46,
          stats_total_players: 140,
          stats_player_count: 10,
          phone_number: 5033136362
        },
        {
          id: 313,
          location: "Pulaski Park",
          city: "Denver",
          day: "Sunday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 67,
          stats_total_players: 111,
          stats_player_count: 13,
          phone_number: 5033136362
        },
        {
          id: 343,
          location: "Five Points Field",
          city: "River North",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Concrete",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 30,
          stats_total_players: 51,
          stats_player_count: 11,
          phone_number: 5033136362
        }
      ]);
    })
    .then(() => {
      // starts the next index at 1000
      return knex.raw("ALTER SEQUENCE games_id_seq RESTART WITH 1000;");
    });
};



