exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("games")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("games").insert([
        {
          id: 151,
          location: "Denver Park Complex",
          city: "Denver",
          // day selction
          day: "Monday",
          // time selection
          time: "Night",
          // level
          level: "Open",
          // field type
          surface: "Turf",
          // goals
          goals: "Netless",
          // info
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          // stats
          stats_games_completed: 45,
          stats_total_players: 119,
          phone_number: 5033136362
        },
        {
          id: 152,
          location: "Washington Park",
          city: "Washington Park",
          day: "Wednesday",
          time: "Morning",
          level: "Normal",
          surface: "Concrete",
          goals: "None",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "None",
          stats_games_completed: 13,
          stats_total_players: 88,
          phone_number: 5033136362
        },
        {
          id: 153,
          location: "Boulder High",
          city: "Boulder",
          day: "Sunday",
          time: "Night",
          level: "Competitive",
          surface: "Concrete",
          goals: "None",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 22,
          stats_total_players: 45,
          phone_number: 5033136362
        },
        {
          id: 154,
          location: "Golden Sports Park",
          city: "Golden",
          day: "Friday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "None",
          info_water:"None",
          info_lights: "Yes",
          stats_games_completed: 9,
          stats_total_players: 29,
          phone_number: 5033136362
        },
        {
          id: 155,
          location: "Arvada Park",
          city: "Arvada",
          day: "Tuesday",
          time: "Night",
          level: "Normal",
          surface: "Grass",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water:"None",
          info_lights: "None",
          stats_games_completed: 29,
          stats_total_players: 119,
          phone_number: 5033136362
        },
        {
          id: 156,
          location: "Sayian Field",
          city: "Ft. Collins",
          day: "Thursday",
          time: "Day",
          level: "Competitive",
          surface: "Concrete",
          goals: "Netless",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "None",
          stats_games_completed: 3,
          stats_total_players: 33,
          phone_number: 5033136362
        },
        {
          id: 157,
          location: "Congress Park",
          city: "Capitol Hill",
          day: "Saturday",
          time: "Night",
          level: "Competitive",
          surface: "Turf",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 11,
          stats_total_players: 98,
          //twilio
          phone_number: 5033136362
        },
        {
          id: 158,
          location: "Cheeseman Park",
          city: "Capitol Hill",
          day: "Tuesday",
          time: "Morning",
          level: "Normal",
          surface: "Dirt",
          goals: "None",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water:"None",
          info_lights: "None",
          stats_games_completed: 21,
          stats_total_players: 44,
          phone_number: 5033136362
        },
        {
          id: 159,
          location: "Colfax Sports Complex",
          city: "Denver",
          day: "Friday",
          time: "Morning",
          level: "Competitive",
          surface: "Turf",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "None",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 41,
          stats_total_players: 119,
          phone_number: 5033136362
        },
        {
          id: 160,
          location: "Longmont Sports Park",
          city: "Longmont",
          day: "Sunday",
          time: "Night",
          level: "Open",
          surface: "Concrete",
          goals: "Full",
          info_parking: "None",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 11,
          stats_total_players: 64,
          phone_number: 5033136362
        },
        {
          id: 161,
          location: "East High School",
          city: "City Park",
          day: "Thursday",
          time: "Day",
          level: "Normal",
          surface: "Dirt",
          goals: "None",
          info_parking:"None",
          info_restrooms: "Yes",
          info_water:"None",
          info_lights: "Yes",
          stats_games_completed: 3,
          stats_total_players: 30,
          phone_number: 5033136362
        },
        {
          id: 162,
          location: "Aroura Sports Park",
          city: "Aroura",
          day: "Saturday",
          time: "Day",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "None",
          stats_games_completed: 20,
          stats_total_players: 99,
          phone_number: 5033136362
        },
        {
          id: 163,
          location: "Sloan's Lake",
          city: "Lakewood",
          day: "Saturday",
          time: "Morning",
          level: "Competitive",
          surface: "Grass",
          goals: "Netless",
          info_parking:"None",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 66,
          stats_total_players: 209,
          phone_number: 5033136362
        },
        {
          id: 164,
          location: "Overland Park",
          city: "Denver",
          day: "Tueday",
          time: "Night",
          level: "Competitive",
          surface: "Turf",
          goals: "None",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 42,
          stats_total_players: 109,
          phone_number: 5033136362
        },
        {
          id: 165,
          location: "RiNo Athletic Fields",
          city: "River North",
          day: "Saturday",
          time: "Day",
          level: "Normal",
          surface: "Turf",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 72,
          stats_total_players: 311,
          phone_number: 5033136362
        },
        {
          id: 166,
          location: "Thorton Fields",
          city: "Thorton",
          day: "Friday",
          time: "Night",
          level: "Open",
          surface: "Grass",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "None",
          info_water: "Yes",
          info_lights: "Yes",
          stats_games_completed: 22,
          stats_total_players: 111,
          phone_number: 5033136362
        },
        {
          id: 167,
          location: "City Park",
          city: "Denver",
          day: "Sunday",
          time: "Day",
          level: "Open",
          surface: "Dirt",
          goals: "Full",
          info_parking: "Yes",
          info_restrooms: "Yes",
          info_water: "None",
          info_lights: "Yes",
          stats_games_completed: 49,
          stats_total_players: 151,
          phone_number: 5033136362
        }
      ]);
    })
    .then(() => {
      // starts the next index at 1000
      return knex.raw("ALTER SEQUENCE games_id_seq RESTART WITH 1000;");
    });
};



